# Generated by Django 4.2.7 on 2025-09-24 23:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre completo')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Correo electrónico')),
                ('telefono', models.CharField(max_length=20, verbose_name='Teléfono')),
                ('nombre_pareja', models.CharField(max_length=255, verbose_name='Nombre de la pareja')),
                ('password_hash', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('REGISTRADO', 'Registrado'), ('CONFIRMADO', 'Confirmado'), ('GANADOR', 'Ganador')], default='REGISTRADO', max_length=20, verbose_name='Estado')),
                ('inserted_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('last_time_winner', models.DateTimeField(blank=True, null=True, verbose_name='Última vez ganador')),
                ('verification_token', models.CharField(blank=True, max_length=255, null=True)),
                ('token_created_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'db_table': 'users',
                'ordering': ['-inserted_at'],
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('ADMIN', 'Administrador'), ('CONCURSANTE', 'Concursante')], max_length=20, verbose_name='Rol')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='api.user', verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Rol',
                'verbose_name_plural': 'Roles',
                'db_table': 'roles',
                'unique_together': {('id_usuario', 'rol')},
            },
        ),
    ]
